services:
  db:
    image: mysql:8.4.4
    container_name: loja_phpoo_mysql
    restart: always
    environment:
      MYSQL_DATABASE: loja_phpoo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: loja_phpoo_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"